- name: "Ansible | Print a operating system"
  debug:
    msg: "The operating system is {{ ansible_distribution }} and {{ ansible_distribution_release }} "

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "empty.yml"


- include_tasks: "{{ item }}"
  with_first_found:
    - "install_{{ ansible_pkg_mgr }}.yml"
    - "empty.yml"




